In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("/Users/bhara-zstch1566/Deep Learning/Projects/AUG-WEEK-2/P2/dataset/titanic/test.csv")
df.drop(["PassengerId","Name"],axis=1)


Pclass     Sex   Age  SibSp  Parch              Ticket      Fare Cabin  \
0         3    male  34.5      0      0              330911    7.8292   NaN   
1         3  female  47.0      1      0              363272    7.0000   NaN   
2         2    male  62.0      0      0              240276    9.6875   NaN   
3         3    male  27.0      0      0              315154    8.6625   NaN   
4         3  female  22.0      1      1             3101298   12.2875   NaN   
..      ...     ...   ...    ...    ...                 ...       ...   ...   
413       3    male   NaN      0      0           A.5. 3236    8.0500   NaN   
414       1  female  39.0      0      0            PC 17758  108.9000  C105   
415       3    male  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN   
416       3    male   NaN      0      0              359309    8.0500   NaN   
417       3    male   NaN      1      1                2668   22.3583   NaN   

    Embarked  
0          Q  
1          S  
2          Q  
3          S  
4          S  
..       ...  
413        S  
414        C  
415        S  
416        S  
417        C  

[418 rows x 9 columns]

In [3]:
Y=pd.read_csv("/Users/bhara-zstch1566/Deep Learning/Projects/AUG-WEEK-2/P2/dataset/titanic/gender_submission.csv").drop("PassengerId",axis=1).to_numpy()
Y


array([[0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
    

In [4]:
df=df.drop(["PassengerId","Name"],axis=1)


In [5]:
df["Sex"] = df["Sex"].map({"male": 0, "female": 1})

df

Pclass  Sex   Age  SibSp  Parch              Ticket      Fare Cabin  \
0         3    0  34.5      0      0              330911    7.8292   NaN   
1         3    1  47.0      1      0              363272    7.0000   NaN   
2         2    0  62.0      0      0              240276    9.6875   NaN   
3         3    0  27.0      0      0              315154    8.6625   NaN   
4         3    1  22.0      1      1             3101298   12.2875   NaN   
..      ...  ...   ...    ...    ...                 ...       ...   ...   
413       3    0   NaN      0      0           A.5. 3236    8.0500   NaN   
414       1    1  39.0      0      0            PC 17758  108.9000  C105   
415       3    0  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN   
416       3    0   NaN      0      0              359309    8.0500   NaN   
417       3    0   NaN      1      1                2668   22.3583   NaN   

    Embarked  
0          Q  
1          S  
2          Q  
3          S  
4          S  
..       ...  
413        S  
414        C  
415        S  
416        S  
417        C  

[418 rows x 9 columns]

In [6]:
df

Pclass  Sex   Age  SibSp  Parch              Ticket      Fare Cabin  \
0         3    0  34.5      0      0              330911    7.8292   NaN   
1         3    1  47.0      1      0              363272    7.0000   NaN   
2         2    0  62.0      0      0              240276    9.6875   NaN   
3         3    0  27.0      0      0              315154    8.6625   NaN   
4         3    1  22.0      1      1             3101298   12.2875   NaN   
..      ...  ...   ...    ...    ...                 ...       ...   ...   
413       3    0   NaN      0      0           A.5. 3236    8.0500   NaN   
414       1    1  39.0      0      0            PC 17758  108.9000  C105   
415       3    0  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN   
416       3    0   NaN      0      0              359309    8.0500   NaN   
417       3    0   NaN      1      1                2668   22.3583   NaN   

    Embarked  
0          Q  
1          S  
2          Q  
3          S  
4          S  
..       ...  
413        S  
414        C  
415        S  
416        S  
417        C  

[418 rows x 9 columns]

In [7]:
set(df["Embarked"])

{'C', 'Q', 'S'}

In [8]:
df["Embarked"]=df["Embarked"].map({'C':1, 'Q':2, 'S':3})

In [9]:
df=df.fillna(0)

In [10]:


df["Ticket"] = df["Ticket"].apply(lambda x: int(x.split()[-1]))


In [11]:
df

Pclass  Sex   Age  SibSp  Parch   Ticket      Fare Cabin  Embarked
0         3    0  34.5      0      0   330911    7.8292     0         2
1         3    1  47.0      1      0   363272    7.0000     0         3
2         2    0  62.0      0      0   240276    9.6875     0         2
3         3    0  27.0      0      0   315154    8.6625     0         3
4         3    1  22.0      1      1  3101298   12.2875     0         3
..      ...  ...   ...    ...    ...      ...       ...   ...       ...
413       3    0   0.0      0      0     3236    8.0500     0         3
414       1    1  39.0      0      0    17758  108.9000  C105         1
415       3    0  38.5      0      0  3101262    7.2500     0         3
416       3    0   0.0      0      0   359309    8.0500     0         3
417       3    0   0.0      1      1     2668   22.3583     0         1

[418 rows x 9 columns]

In [30]:
df["Cabin"]=df["Cabin"].apply(lambda x: int(x) if x==0 else 1)

In [34]:
df.iloc[12]

Pclass          1.0000
Sex             1.0000
Age            23.0000
SibSp           1.0000
Parch           0.0000
Ticket      21228.0000
Fare           82.2667
Cabin           1.0000
Embarked        3.0000
Name: 12, dtype: float64

In [35]:
X=df.to_numpy()

In [36]:
X
np.nan_to_num(X)

array([[ 3.    ,  0.    , 34.5   , ...,  7.8292,  0.    ,  2.    ],
       [ 3.    ,  1.    , 47.    , ...,  7.    ,  0.    ,  3.    ],
       [ 2.    ,  0.    , 62.    , ...,  9.6875,  0.    ,  2.    ],
       ...,
       [ 3.    ,  0.    , 38.5   , ...,  7.25  ,  0.    ,  3.    ],
       [ 3.    ,  0.    ,  0.    , ...,  8.05  ,  0.    ,  3.    ],
       [ 3.    ,  0.    ,  0.    , ..., 22.3583,  0.    ,  1.    ]],
      shape=(418, 9))

In [37]:
X[0].astype(float)

array([3.00000e+00, 0.00000e+00, 3.45000e+01, 0.00000e+00, 0.00000e+00,
       3.30911e+05, 7.82920e+00, 0.00000e+00, 2.00000e+00])

In [38]:
for i in range(len(X)):
    print(X[i])
    X[i]=X[i].astype(int)

[3.00000e+00 0.00000e+00 3.45000e+01 0.00000e+00 0.00000e+00 3.30911e+05
 7.82920e+00 0.00000e+00 2.00000e+00]
[3.00000e+00 1.00000e+00 4.70000e+01 1.00000e+00 0.00000e+00 3.63272e+05
 7.00000e+00 0.00000e+00 3.00000e+00]
[2.00000e+00 0.00000e+00 6.20000e+01 0.00000e+00 0.00000e+00 2.40276e+05
 9.68750e+00 0.00000e+00 2.00000e+00]
[3.00000e+00 0.00000e+00 2.70000e+01 0.00000e+00 0.00000e+00 3.15154e+05
 8.66250e+00 0.00000e+00 3.00000e+00]
[3.000000e+00 1.000000e+00 2.200000e+01 1.000000e+00 1.000000e+00
 3.101298e+06 1.228750e+01 0.000000e+00 3.000000e+00]
[3.000e+00 0.000e+00 1.400e+01 0.000e+00 0.000e+00 7.538e+03 9.225e+00
 0.000e+00 3.000e+00]
[3.00000e+00 1.00000e+00 3.00000e+01 0.00000e+00 0.00000e+00 3.30972e+05
 7.62920e+00 0.00000e+00 2.00000e+00]
[2.00000e+00 0.00000e+00 2.60000e+01 1.00000e+00 1.00000e+00 2.48738e+05
 2.90000e+01 0.00000e+00 3.00000e+00]
[3.0000e+00 1.0000e+00 1.8000e+01 0.0000e+00 0.0000e+00 2.6570e+03
 7.2292e+00 0.0000e+00 1.0000e+00]
[3.0000e+00 0.0000e

In [39]:
X[12]

array([1.0000e+00, 1.0000e+00, 2.3000e+01, 1.0000e+00, 0.0000e+00,
       2.1228e+04, 8.2000e+01, 1.0000e+00, 3.0000e+00])

In [41]:
X.dtype

dtype('float64')

In [42]:
X.shape

(418, 9)

In [43]:
# titanic_preprocessing.py

import numpy as np
import pandas as pd

# -----------------------------
# Load data
# -----------------------------
df = pd.read_csv("/Users/bhara-zstch1566/Deep Learning/Projects/AUG-WEEK-2/P2/dataset/titanic/test.csv")
Y = pd.read_csv("/Users/bhara-zstch1566/Deep Learning/Projects/AUG-WEEK-2/P2/dataset/titanic/gender_submission.csv")
Y = Y.drop("PassengerId", axis=1).to_numpy()

# -----------------------------
# Drop unnecessary columns
# -----------------------------
df = df.drop(["PassengerId", "Name"], axis=1)

# -----------------------------
# Encode categorical variables
# -----------------------------
df["Sex"] = df["Sex"].map({"male": 0, "female": 1})
df["Embarked"] = df["Embarked"].map({'C': 1, 'Q': 2, 'S': 3})

# -----------------------------
# Handle missing values
# -----------------------------
df = df.fillna(0)

# -----------------------------
# Process Ticket column
# Extract numeric part if available, otherwise set to 0
# -----------------------------
def ticket_to_num(ticket):
    parts = ticket.split()
    if parts[-1].isdigit():
        return int(parts[-1])
    return 0

df["Ticket"] = df["Ticket"].apply(ticket_to_num)

# -----------------------------
# Process Cabin column
# Convert to 0 if missing (already 0 from fillna),
# otherwise mark presence as 1
# -----------------------------
df["Cabin"] = df["Cabin"].apply(lambda x: 0 if x == 0 else 1)

# -----------------------------
# Convert DataFrame to NumPy array
# -----------------------------
X = df.to_numpy()
X = np.nan_to_num(X).astype(float)

print("Feature matrix shape:", X.shape)
print("Label shape:", Y.shape)
print("Sample row (X[12]):", X[12])


Feature matrix shape: (418, 9)
Label shape: (418, 1)
Sample row (X[12]): [1.00000e+00 1.00000e+00 2.30000e+01 1.00000e+00 0.00000e+00 2.12280e+04
 8.22667e+01 1.00000e+00 3.00000e+00]
